spring.application.name=sabor-peruano
spring.datasource.url=jdbc:mysql://192.168.100.160:3307/db_sabor_peruano
spring.datasource.username=desarrollador
spring.datasource.password=suaqBXAqXy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080